# LAB 1 - INTRO TO PYTHON

This lab is comprised of three parts:

- 1. Introduction to Jupyter Notebooks

- 2. Python Language and NumPy Library

- 3. Data Manipulation with Pandas Library


## 1. INTRODUCTION TO JUPYTER NOTEBOOKS

Open the file "Lab1.ipynb"

`"File -> Open..."` 

Navigate to where you saved the files you downloaded for this class and double click on the "Lab1.ipynb" file

### Running notebook cells

The notebook is divided into cells. Each cell can contain texts, codes or html scripts. Running a non-code cell simply advances to the next cell. Make sure to type commands always in a Code cell. You can verify this by checking the scroll-down window in the above toolbar menu.

To run a code cell use `Shift + Enter` or `Ctrl + Enter`. In Mac, `Shift + Enter` or `Command + Enter`. 

Try running these lines:

In [4]:
8*6

48

In [5]:
2**16

65536

Incomplete command, Jupyter will display a `SyntaxError`

In [8]:
2^

SyntaxError: invalid syntax (<ipython-input-8-0deb74d06d3d>, line 1)

Your turn:

In [6]:
# EXERCISE: Compute 284455 divided by 3.67778



In Python, any text following a hash sign in a code cell is a comment

### Interrupting the kernel

For debugging, often we would like to interupt the current running process. This can be done by pressing the stop button. 

When a processing is running, the circle on the right upper corner is filled. When idle, the circle is empty.

Interrupting sometimes does not work. You can reset the state by restarting the kernel. This is done by clicking Kernel/Restart or the Refresh button in the toolbar above.

### Undoing

To undo changes in each cell, hit `Command-z` for Mac and `Ctrl-z` for Windows.
To undo `Delete Cell`, select `Edit->Undo Delete Cell`.

### Saving the notebook

To save your notebook, either select `"File->Save and Checkpoint"` or hit `Command-s` for Mac and `Ctrl-s` for Windows

### Other Notebook tips
- To add a new cell, either select `"Insert->Insert New Cell Below"` or click the white plus button
- You can change the cell mode from code to text in the pulldown menu by selecting `Markdown`.
- `Help->Keyboard Shortcuts` has a list of keyboard shortcuts

## 2. PYTHON LANGUAGE AND NUMPY LIBRARY

##  Data Types

### Floats and Integers

In [177]:
x = 4
print(x, type(x))

4 <class 'int'>


In [176]:
x = 1 / 4
print(x, type(x))

0.25 <class 'float'>


### Strings

Double quotes and single quotes are the same thing. Both represent strings. `'+'` concatenates strings

In [179]:
"IEOR " + '242'

'IEOR 242'

### Lists

A list is a mutable collection of data. That is we can change it after we create it. They can be created using square brackets []


Important functions: 
- `'+'` appends lists. 
- `len(x)` to get length

In [180]:
x = ["IEOR"] + [2, 4, 2]
print(x)

['IEOR', 2, 4, 2]


In [181]:
print(len(x))

4


### Tuples

A tuple is an immutable collection of data. They can be created using round brackets (). 
They are usually used as inputs and outputs to functions.

In [182]:
t = ("I", "E", "O", "R") + (2, 4, 2)
print(t)

('I', 'E', 'O', 'R', 2, 4, 2)


In [162]:
# Cannot do assignment to a tuple after creation - it's immutable
t[4] = 3 # will error

# Note: errors in notebook appear inline

TypeError: 'tuple' object does not support item assignment

## Functions and Variables

A function can take in several arguments or inputs, and returns an output value.
Python has some built-in functions:

In [183]:
abs(-65)

65

In [239]:
max([2, 4, 2])

4

In [240]:
# Get help on any function:
max?

Basic variable naming rules: 
- Don't use spaces (underscores or capital letters instead)
- Don't start names with a number
- Variable names are case sensitive - capital and lowercase letters are different

In [ ]:
# EXERCISE: 
# Create a variable called "SecondsDay" that is equal to the number of seconds in a day, and output its value.



### User-defined Functions

We can define functions ourselves, by using `def` and passing the expected inputs, as well as stating the returned output.
In this example we create a function that takes two numbers `x` and `y`, and returns the sum.

In [2]:
def my_function(x, y):
    
    result = x+y
    
    return result

In [3]:
my_function(5, 3)

8

## Linear Algebra with Numpy

The numpy array, aka an "ndarray", is like a list with multidimensional support and more functions.
https://numpy.org/doc/stable/reference/routines.linalg.html

Important NumPy Array functions:

- `.shape` returns the dimensions of the array.

- `.ndim` returns the number of dimensions. 

- `.size` returns the number of entries in the array.

- `len()` returns the first dimension.


To use functions in NumPy, we have to import NumPy to our workspace. This is done by the command `import numpy`. By convention, we rename `numpy` as `np` for convenience.

### Arrays

In [191]:
import numpy as np

a = np.array([1,2,3])
a.shape

(3,)

In [192]:
2*a

array([2, 4, 6])

In [197]:
# Element-wise multiplication
b = np.array([3,3,3])
np.multiply(a,b)

array([3, 6, 9])

In [198]:
# Inner product
inner_product = np.dot(a,b)
print(inner_product)

18


### Slicing

Numpy uses pass-by-reference semantics so it creates views into the existing array, without implicit copying. This is particularly helpful with very large arrays because copying can be slow.

In [204]:
y = x[0:4]
print(y)

[[1 2]
 [3 4]]


Because slicing does not copy the array, changing `y` changes `x`. To actually copy x, we should use `.copy()`. 

### Matrices

In [206]:
# Create a matrix
A = np.array([[1, 2, 8],
             [3, 2, 9]])
print(A)

[[1 2 8]
 [3 2 9]]


In [201]:
# Matrix multiplication
B = np.array([[1, 2],
              [3, 8],
              [2, 9]])

# There are tow ways to perform matrix multiplication:
print(np.matmul(A,B))

# Alternatively:
print(A@B)

[[ 23  90]
 [ 27 103]]
[[ 23  90]
 [ 27 103]]


In [202]:
# Transpose a matrix
A.T

array([[1, 3],
       [2, 2],
       [8, 9]])

In [203]:
# Compute the inverse
C = np.array([[1, 2],
             [3, 2]])
D = np.linalg.inv(C)
C@D

array([[1.00000000e+00, 5.55111512e-17],
       [0.00000000e+00, 1.00000000e+00]])

## 3. DATA MANIPULATION WITH PANDAS LIBRARY

`pandas` is designed to make it easier to work with structured data. Most of the analyses you might perform will likely involve using tabular data, e.g., from .csv files or relational databases (e.g., SQL). The `DataFrame` object in `pandas` is "a two-dimensional tabular, column-oriented data structure with both row and column labels."

If you're curious:

>The `pandas` name itself is derived from *panel data*, an econometrics term for multidimensional structured data sets, and *Python data analysis* itself. After getting introduced, you can consult the full [`pandas` documentation](http://pandas.pydata.org/pandas-docs/stable/).

### Setting the working directory

Before loading the data, let's begin by setting the right working directory. In order to change the working directory, we use the `os` library

In [209]:
import os
os.getcwd()

"/Users/stefanozavagli/Documents/Carrera/Jobs/Berkeley/Teaching/242 Sp '21/Lab1"

Change the working directory to whichever path has your python files and data files

In [213]:
os.chdir("new_path")

### Loading CSV files

Now we can use the `pandas` library to load the data. Import `pandas` using the conventional abbreviation and call the `read_csv` method on your file's path name

In [216]:
import pandas as pd

# WHO = pd.read_csv("WHO.csv")
WHO = pd.read_csv("WHO.csv", encoding = "ISO-8859-1") ##check this encoding, also encoding = 'unicode_escape'

### The Dataframe

In [215]:
WHO

Country                 Region  Population  \
0                           Afghanistan  Eastern Mediterranean       29825   
1                               Albania                 Europe        3162   
2                               Algeria                 Africa       38482   
3                               Andorra                 Europe          78   
4                                Angola                 Africa       20821   
..                                  ...                    ...         ...   
189  Venezuela (Bolivarian Republic of)               Americas       29955   
190                            Viet Nam        Western Pacific       90796   
191                               Yemen  Eastern Mediterranean       23852   
192                              Zambia                 Africa       14075   
193                            Zimbabwe                 Africa       13724   

     Under15  Over60  FertilityRate  LifeExpectancy  ChildMortality  \
0      47.42    3.82           5.40              60            98.5   
1      21.33   14.93           1.75              74            16.7   
2      27.42    7.17           2.83              73            20.0   
3      15.20   22.86            NaN              82             3.2   
4      47.58    3.84           6.10              51           163.5   
..       ...     ...            ...             ...             ...   
189    28.84    9.17           2.44              75            15.3   
190    22.87    9.32           1.79              75            23.0   
191    40.72    4.54           4.35              64            60.0   
192    46.73    3.95           5.77              55            88.5   
193    40.24    5.68           3.64              54            89.8   

     CellularSubscribers  LiteracyRate      GNI  PrimarySchoolEnrollmentMale  \
0                  54.26           NaN   1140.0                          NaN   
1                  96.39           NaN   8820.0                          NaN   
2                  98.99           NaN   8310.0                         98.2   
3                  75.49           NaN      NaN                         78.4   
4                  48.38          70.1   5230.0                         93.1   
..                   ...           ...      ...                          ...   
189                97.78           NaN  12430.0                         94.7   
190               143.39          93.2   3250.0                          NaN   
191                47.05          63.9   2170.0                         85.5   
192                60.59          71.2   1490.0                         91.4   
193                72.13          92.2      NaN                          NaN   

     PrimarySchoolEnrollmentFemale  
0                              NaN  
1                              NaN  
2                             96.4  
3                             79.4  
4                             78.2  
..                             ...  
189                           95.1  
190                            NaN  
191                           70.5  
192                           93.9  
193                            NaN  

[194 rows x 13 columns]

In [217]:
# Structure of the data
WHO.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Country                        194 non-null    object 
 1   Region                         194 non-null    object 
 2   Population                     194 non-null    int64  
 3   Under15                        194 non-null    float64
 4   Over60                         194 non-null    float64
 5   FertilityRate                  183 non-null    float64
 6   LifeExpectancy                 194 non-null    int64  
 7   ChildMortality                 194 non-null    float64
 8   CellularSubscribers            184 non-null    float64
 9   LiteracyRate                   103 non-null    float64
 10  GNI                            162 non-null    float64
 11  PrimarySchoolEnrollmentMale    101 non-null    float64
 12  PrimarySchoolEnrollmentFemale  101 non-null    flo

In [228]:
# Recent statistics from the World Health Organization (WHO)
# The variables are: 
# the name of the country
# the region the country is in
# the population in thousandsa
# the percentage of the population under 15 and over 60
# the fertility rate (average number of children per woman)
# the Life Expectancy in years
# the Child Mortality rate (the number of children who die by age 5 per 1000 births)
# the number of cellular subscribers per 100 population
# the literacy rate among adults aged >= 15
# the gross national income per capita
# the percentage of male children enrolled in primary school
# the percentage of female children enrolled in primary school

In [26]:
# Statistical summary of the data:
WHO.describe()

Population     Under15      Over60  FertilityRate  LifeExpectancy  \
count  1.940000e+02  194.000000  194.000000     183.000000      194.000000   
mean   3.635997e+04   28.732423   11.163660       2.940656       70.010309   
std    1.379031e+05   10.534573    7.149331       1.480984        9.259075   
min    1.000000e+00   13.120000    0.810000       1.260000       47.000000   
25%    1.695750e+03   18.717500    5.200000       1.835000       64.000000   
50%    7.790000e+03   28.650000    8.530000       2.400000       72.500000   
75%    2.453525e+04   37.752500   16.687500       3.905000       76.000000   
max    1.390000e+06   49.990000   31.920000       7.580000       83.000000   

       ChildMortality  CellularSubscribers  LiteracyRate           GNI  \
count      194.000000           184.000000    103.000000    162.000000   
mean        36.148969            93.641522     83.710680  13320.925926   
std         37.992935            41.400447     17.530645  15192.988650   
min          2.200000             2.570000     31.100000    340.000000   
25%          8.425000            63.567500     71.600000   2335.000000   
50%         18.600000            97.745000     91.800000   7870.000000   
75%         55.975000           120.805000     97.850000  17557.500000   
max        181.600000           196.410000     99.800000  86440.000000   

       PrimarySchoolEnrollmentMale  PrimarySchoolEnrollmentFemale  
count                   101.000000                     101.000000  
mean                     90.850495                      89.632673  
std                      11.017147                      12.817614  
min                      37.200000                      32.500000  
25%                      87.700000                      87.300000  
50%                      94.700000                      95.100000  
75%                      98.100000                      97.900000  
max                     100.000000                     100.000000

In [219]:
# Display a few data points at the "head" (start) of the dataset, i.e. the first few records
WHO.head()

Country                 Region  Population  Under15  Over60  \
0          Afghanistan  Eastern Mediterranean       29825    47.42    3.82   
1              Albania                 Europe        3162    21.33   14.93   
2              Algeria                 Africa       38482    27.42    7.17   
3              Andorra                 Europe          78    15.20   22.86   
4               Angola                 Africa       20821    47.58    3.84   
5  Antigua and Barbuda               Americas          89    25.96   12.35   

   FertilityRate  LifeExpectancy  ChildMortality  CellularSubscribers  \
0           5.40              60            98.5                54.26   
1           1.75              74            16.7                96.39   
2           2.83              73            20.0                98.99   
3            NaN              82             3.2                75.49   
4           6.10              51           163.5                48.38   
5           2.12              75             9.9               196.41   

   LiteracyRate      GNI  PrimarySchoolEnrollmentMale  \
0           NaN   1140.0                          NaN   
1           NaN   8820.0                          NaN   
2           NaN   8310.0                         98.2   
3           NaN      NaN                         78.4   
4          70.1   5230.0                         93.1   
5          99.0  17900.0                         91.1   

   PrimarySchoolEnrollmentFemale  
0                            NaN  
1                            NaN  
2                           96.4  
3                           79.4  
4                           78.2  
5                           84.5

In [221]:
# The last 6 records
WHO.tail(6)

Country                 Region  Population  \
188                             Vanuatu        Western Pacific         247   
189  Venezuela (Bolivarian Republic of)               Americas       29955   
190                            Viet Nam        Western Pacific       90796   
191                               Yemen  Eastern Mediterranean       23852   
192                              Zambia                 Africa       14075   
193                            Zimbabwe                 Africa       13724   

     Under15  Over60  FertilityRate  LifeExpectancy  ChildMortality  \
188    37.37    6.02           3.46              72            17.9   
189    28.84    9.17           2.44              75            15.3   
190    22.87    9.32           1.79              75            23.0   
191    40.72    4.54           4.35              64            60.0   
192    46.73    3.95           5.77              55            88.5   
193    40.24    5.68           3.64              54            89.8   

     CellularSubscribers  LiteracyRate      GNI  PrimarySchoolEnrollmentMale  \
188                55.76          82.6   4330.0                          NaN   
189                97.78           NaN  12430.0                         94.7   
190               143.39          93.2   3250.0                          NaN   
191                47.05          63.9   2170.0                         85.5   
192                60.59          71.2   1490.0                         91.4   
193                72.13          92.2      NaN                          NaN   

     PrimarySchoolEnrollmentFemale  
188                            NaN  
189                           95.1  
190                            NaN  
191                           70.5  
192                           93.9  
193                            NaN

### Subsets of data

In [223]:
# Subset with only the countries in Europe
WHO_Europe = WHO[WHO['Region'] == 'Europe']
WHO_Europe.head()

Country  Region  Population  Under15  Over60  FertilityRate  \
1      Albania  Europe        3162    21.33   14.93           1.75   
3      Andorra  Europe          78    15.20   22.86            NaN   
7      Armenia  Europe        2969    20.34   14.06           1.74   
9      Austria  Europe        8464    14.51   23.52           1.44   
10  Azerbaijan  Europe        9309    22.25    8.24           1.96   

    LifeExpectancy  ChildMortality  CellularSubscribers  LiteracyRate  \
1               74            16.7                96.39           NaN   
3               82             3.2                75.49           NaN   
7               71            16.4               103.57          99.6   
9               81             4.0               154.78           NaN   
10              71            35.2               108.75           NaN   

        GNI  PrimarySchoolEnrollmentMale  PrimarySchoolEnrollmentFemale  
1    8820.0                          NaN                            NaN  
3       NaN                         78.4                           79.4  
7    6100.0                          NaN                            NaN  
9   42050.0                          NaN                            NaN  
10   8960.0                         85.3                           84.1

In [224]:
WHO_Europe.count()

Country                          53
Region                           53
Population                       53
Under15                          53
Over60                           53
FertilityRate                    50
LifeExpectancy                   53
ChildMortality                   53
CellularSubscribers              51
LiteracyRate                     26
GNI                              48
PrimarySchoolEnrollmentMale      38
PrimarySchoolEnrollmentFemale    38
dtype: int64

In [226]:
# Other subsets
WHO_AsiaEurope = WHO[(WHO['Region'] == 'Europe') | (WHO['Region'] == 'South-East Asia') | (WHO['Region'] == "Eastern Mediterranean")] 
WHO_AsiaEurope.count()

Country                          86
Region                           86
Population                       86
Under15                          86
Over60                           86
FertilityRate                    83
LifeExpectancy                   86
ChildMortality                   86
CellularSubscribers              83
LiteracyRate                     41
GNI                              69
PrimarySchoolEnrollmentMale      48
PrimarySchoolEnrollmentFemale    48
dtype: int64

### Saving dataframe to CSV file

In [75]:
WHO_AsiaEurope.to_csv("WHO_AsiaEurope.csv")

In [ ]:
# EXERCISE: How many countries have population greater than 50 million? 



In [79]:
Answer = WHO[WHO['Population'] > 50000]
len(Answer)

25

### More Data Analysis

To access a variable in a data frame, you always have to link it to the data frame and call it using square brackets and pass it's name as a string.

In [229]:
# This will give you an error!
LifeExpectancy

NameError: name 'LifeExpectancy' is not defined

In [230]:
# Now, run this.
WHO['LifeExpectancy']

0      60
1      74
2      73
3      82
4      51
       ..
189    75
190    75
191    64
192    55
193    54
Name: LifeExpectancy, Length: 194, dtype: int64

### Statistics

In [231]:
# Statistics about this variable
print((WHO['LifeExpectancy'].mean()))
print((WHO['LifeExpectancy'].max()))
print((WHO['LifeExpectancy'].min()))

70.01030927835052
83
47


In [232]:
# Standard deviation
WHO['LifeExpectancy'].std
WHO['LifeExpectancy'].describe()

count    194.000000
mean      70.010309
std        9.259075
min       47.000000
25%       64.000000
50%       72.500000
75%       76.000000
max       83.000000
Name: LifeExpectancy, dtype: float64

In [233]:
WHO['GNI'].describe()

# What's different here?



count      162.000000
mean     13320.925926
std      15192.988650
min        340.000000
25%       2335.000000
50%       7870.000000
75%      17557.500000
max      86440.000000
Name: GNI, dtype: float64

In [234]:
# Identify countries corresponding to max and min
idx_min = WHO['LifeExpectancy'].argmin()
print(WHO['Country'][idx_min])

idx_max = WHO['LifeExpectancy'].argmax()
print(WHO['Country'][idx_max])

Sierra Leone
Japan


In [ ]:
# EXERCISE:
# What is the largest population value among all countries?
# Which country has the largest population?



### Dealing with missing data

In [235]:
# Dealing with NAs
# Try:
WHO['LiteracyRate'].head()

0     NaN
1     NaN
2     NaN
3     NaN
4    70.1
Name: LiteracyRate, dtype: float64

In [236]:
WHO['LiteracyRate'].dropna(inplace=True)
WHO['LiteracyRate'].head()

4     70.1
5     99.0
6     97.8
7     99.6
12    91.9
Name: LiteracyRate, dtype: float64

# References
- [1] Special thanks to the [EECS127 Fall 2019](https://inst.eecs.berkeley.edu/~ee127/fa19/) for providing a great starting point for Intro to Jupyter
- [2] D-lab intro to Pandas
- [3] The official Python 3 language documentation. [Link](https://docs.python.org/3/).
- [4] The official NumPy and SciPy documentation. [Link](https://docs.scipy.org/doc/).


