# LAB 1 - INTRO TO JUPYTER ENVIRONMENT AND PYTHON LANGUAGE

This lab is comprised of four parts:

- 1) Introduction to Jupyter Environment and Python Language

- 2) Setting the working directory

- 3) Loading data from a csv file

- 4) Basic data manipulations - Dataframes


## 1) INTRODUCTION TO JUPYTER ENVIRONMENT AND PYTHON LANGUAGE

In Python everything following a hash sign is a comment

Open the file 'Lab1.ipynb'

File -> Open... 

Navigate to where you saved the files you downloaded for this class and double click on the 'Lab1.ipynb' file

### BASIC CALCULATIONS IN PYTHON

Make sure to type commands always in a Code cell. You can verify this by checking the scroll-down window in the above toolbar menu.

To run a cell, press Shift+Enter

Try running these lines:

In [5]:
8*6

48

In [6]:
2**16

65536

Incomplete command, Jupyter will display a SyntaxError

In [8]:
2^

SyntaxError: invalid syntax (<ipython-input-8-0deb74d06d3d>, line 1)

Your turn:

In [11]:
# TO DO: Compute 284455 divided by 3.67778
28455/3.6778

7736.962314427104

### FUNCTIONS AND VARIABLES

In [3]:
# A function can take in several arguments or inputs, and returns an output value.
# Ex: square root and absolute value functions:
abs(-65)

65

In [16]:
# Some functions are not built into Python, and they have to be imported from a library.
# NumPy is a very useful library comprising thousands of mathematical functions: 
# https://numpy.org/doc/stable/reference/index.html
import numpy as np

np.sqrt(2)

1.4142135623730951

In [32]:
# Get help on any function:
np.sqrt?

In [18]:
# Save the output to a variable. 
SquareRoot2 = np.sqrt(2) 

In [15]:
# See the value by typing its name
SquareRoot2

1.4142135623730951

In [21]:
# You can also see an output by using the print() function
print(SquareRoot2)

1.4142135623730951


In [ ]:
# Basic variable naming rules: 
# Don't use spaces (underscores or capital letters instead)
# Don't start names with a number
# Variable names are case sensitive - capital and lowercase letters are different

In [ ]:
# Your turn:
# Create a variable called "SecondsDay" that is equal to the number of seconds in a day, and output its value.

### SETTING THE WORKING DIRECTORY

In [2]:
# In order to change the working directory, we use the 'os' library
import os

os.getcwd()

"/Users/stefanozavagli/Documents/Carrera/Jobs/Berkeley/Teaching/242 Sp '21/Lab1"

In [3]:
# This changes the working directory to the one you choos
os.chdir("new_path")

FileNotFoundError: [Errno 2] No such file or directory: 'new_path'

### LOADING CSV FILES

In [17]:
# Read in the data file 
import pandas as pd

# WHO = pd.read_csv("WHO.csv")
WHO = pd.read_csv("WHO.csv", encoding = "ISO-8859-1") ##check this encoding, also encoding = 'unicode_escape'
WHO

Country                 Region  Population  \
0                           Afghanistan  Eastern Mediterranean       29825   
1                               Albania                 Europe        3162   
2                               Algeria                 Africa       38482   
3                               Andorra                 Europe          78   
4                                Angola                 Africa       20821   
..                                  ...                    ...         ...   
189  Venezuela (Bolivarian Republic of)               Americas       29955   
190                            Viet Nam        Western Pacific       90796   
191                               Yemen  Eastern Mediterranean       23852   
192                              Zambia                 Africa       14075   
193                            Zimbabwe                 Africa       13724   

     Under15  Over60  FertilityRate  LifeExpectancy  ChildMortality  \
0      47.42    3.82           5.40              60            98.5   
1      21.33   14.93           1.75              74            16.7   
2      27.42    7.17           2.83              73            20.0   
3      15.20   22.86            NaN              82             3.2   
4      47.58    3.84           6.10              51           163.5   
..       ...     ...            ...             ...             ...   
189    28.84    9.17           2.44              75            15.3   
190    22.87    9.32           1.79              75            23.0   
191    40.72    4.54           4.35              64            60.0   
192    46.73    3.95           5.77              55            88.5   
193    40.24    5.68           3.64              54            89.8   

     CellularSubscribers  LiteracyRate      GNI  PrimarySchoolEnrollmentMale  \
0                  54.26           NaN   1140.0                          NaN   
1                  96.39           NaN   8820.0                          NaN   
2                  98.99           NaN   8310.0                         98.2   
3                  75.49           NaN      NaN                         78.4   
4                  48.38          70.1   5230.0                         93.1   
..                   ...           ...      ...                          ...   
189                97.78           NaN  12430.0                         94.7   
190               143.39          93.2   3250.0                          NaN   
191                47.05          63.9   2170.0                         85.5   
192                60.59          71.2   1490.0                         91.4   
193                72.13          92.2      NaN                          NaN   

     PrimarySchoolEnrollmentFemale  
0                              NaN  
1                              NaN  
2                             96.4  
3                             79.4  
4                             78.2  
..                             ...  
189                           95.1  
190                            NaN  
191                           70.5  
192                           93.9  
193                            NaN  

[194 rows x 13 columns]

In [38]:
# Structure of the data
WHO.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Country                        194 non-null    object 
 1   Region                         194 non-null    object 
 2   Population                     194 non-null    int64  
 3   Under15                        194 non-null    float64
 4   Over60                         194 non-null    float64
 5   FertilityRate                  183 non-null    float64
 6   LifeExpectancy                 194 non-null    int64  
 7   ChildMortality                 194 non-null    float64
 8   CellularSubscribers            184 non-null    float64
 9   LiteracyRate                   103 non-null    float64
 10  GNI                            162 non-null    float64
 11  PrimarySchoolEnrollmentMale    101 non-null    float64
 12  PrimarySchoolEnrollmentFemale  101 non-null    flo

In [39]:
# Recent statistics from the World Health Organization (WHO)
# The variables are: 
# the name of the country
# the region the country is in
# the population in thousandsa
# the percentage of the population under 15 and over 60
# the fertility rate (average number of children per woman)
# the Life Expectancy in years
# the Child Mortality rate (the number of children who die by age 5 per 1000 births)
# the number of cellular subscribers per 100 population
# the literacy rate among adults aged >= 15
# the gross national income per capita
# the percentage of male children enrolled in primary school
# the percentage of female children enrolled in primary school

In [26]:
# Statistical summary of the data:
WHO.describe()

Population     Under15      Over60  FertilityRate  LifeExpectancy  \
count  1.940000e+02  194.000000  194.000000     183.000000      194.000000   
mean   3.635997e+04   28.732423   11.163660       2.940656       70.010309   
std    1.379031e+05   10.534573    7.149331       1.480984        9.259075   
min    1.000000e+00   13.120000    0.810000       1.260000       47.000000   
25%    1.695750e+03   18.717500    5.200000       1.835000       64.000000   
50%    7.790000e+03   28.650000    8.530000       2.400000       72.500000   
75%    2.453525e+04   37.752500   16.687500       3.905000       76.000000   
max    1.390000e+06   49.990000   31.920000       7.580000       83.000000   

       ChildMortality  CellularSubscribers  LiteracyRate           GNI  \
count      194.000000           184.000000    103.000000    162.000000   
mean        36.148969            93.641522     83.710680  13320.925926   
std         37.992935            41.400447     17.530645  15192.988650   
min          2.200000             2.570000     31.100000    340.000000   
25%          8.425000            63.567500     71.600000   2335.000000   
50%         18.600000            97.745000     91.800000   7870.000000   
75%         55.975000           120.805000     97.850000  17557.500000   
max        181.600000           196.410000     99.800000  86440.000000   

       PrimarySchoolEnrollmentMale  PrimarySchoolEnrollmentFemale  
count                   101.000000                     101.000000  
mean                     90.850495                      89.632673  
std                      11.017147                      12.817614  
min                      37.200000                      32.500000  
25%                      87.700000                      87.300000  
50%                      94.700000                      95.100000  
75%                      98.100000                      97.900000  
max                     100.000000                     100.000000

In [28]:
# Display a few data points at the "head" (start) of the dataset
# The first 6 records
WHO.head()

Country                 Region  Population  \
189  Venezuela (Bolivarian Republic of)               Americas       29955   
190                            Viet Nam        Western Pacific       90796   
191                               Yemen  Eastern Mediterranean       23852   
192                              Zambia                 Africa       14075   
193                            Zimbabwe                 Africa       13724   

     Under15  Over60  FertilityRate  LifeExpectancy  ChildMortality  \
189    28.84    9.17           2.44              75            15.3   
190    22.87    9.32           1.79              75            23.0   
191    40.72    4.54           4.35              64            60.0   
192    46.73    3.95           5.77              55            88.5   
193    40.24    5.68           3.64              54            89.8   

     CellularSubscribers  LiteracyRate      GNI  PrimarySchoolEnrollmentMale  \
189                97.78           NaN  12430.0                         94.7   
190               143.39          93.2   3250.0                          NaN   
191                47.05          63.9   2170.0                         85.5   
192                60.59          71.2   1490.0                         91.4   
193                72.13          92.2      NaN                          NaN   

     PrimarySchoolEnrollmentFemale  
189                           95.1  
190                            NaN  
191                           70.5  
192                           93.9  
193                            NaN

In [29]:
# The last few records
WHO.tail()

Country                 Region  Population  \
189  Venezuela (Bolivarian Republic of)               Americas       29955   
190                            Viet Nam        Western Pacific       90796   
191                               Yemen  Eastern Mediterranean       23852   
192                              Zambia                 Africa       14075   
193                            Zimbabwe                 Africa       13724   

     Under15  Over60  FertilityRate  LifeExpectancy  ChildMortality  \
189    28.84    9.17           2.44              75            15.3   
190    22.87    9.32           1.79              75            23.0   
191    40.72    4.54           4.35              64            60.0   
192    46.73    3.95           5.77              55            88.5   
193    40.24    5.68           3.64              54            89.8   

     CellularSubscribers  LiteracyRate      GNI  PrimarySchoolEnrollmentMale  \
189                97.78           NaN  12430.0                         94.7   
190               143.39          93.2   3250.0                          NaN   
191                47.05          63.9   2170.0                         85.5   
192                60.59          71.2   1490.0                         91.4   
193                72.13          92.2      NaN                          NaN   

     PrimarySchoolEnrollmentFemale  
189                           95.1  
190                            NaN  
191                           70.5  
192                           93.9  
193                            NaN

In [33]:
# 4. BASIC DATA MANIPULATIONS AND ANALYSIS - DATA FRAMES.
# Subset with only the countries in Europe
WHO_Europe = WHO[WHO['Region'] == 'Europe']
WHO_Europe.head()

Country  Region  Population  Under15  Over60  FertilityRate  \
1      Albania  Europe        3162    21.33   14.93           1.75   
3      Andorra  Europe          78    15.20   22.86            NaN   
7      Armenia  Europe        2969    20.34   14.06           1.74   
9      Austria  Europe        8464    14.51   23.52           1.44   
10  Azerbaijan  Europe        9309    22.25    8.24           1.96   

    LifeExpectancy  ChildMortality  CellularSubscribers  LiteracyRate  \
1               74            16.7                96.39           NaN   
3               82             3.2                75.49           NaN   
7               71            16.4               103.57          99.6   
9               81             4.0               154.78           NaN   
10              71            35.2               108.75           NaN   

        GNI  PrimarySchoolEnrollmentMale  PrimarySchoolEnrollmentFemale  
1    8820.0                          NaN                            NaN  
3       NaN                         78.4                           79.4  
7    6100.0                          NaN                            NaN  
9   42050.0                          NaN                            NaN  
10   8960.0                         85.3                           84.1

In [37]:
WHO_Europe.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53 entries, 1 to 187
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Country                        53 non-null     object 
 1   Region                         53 non-null     object 
 2   Population                     53 non-null     int64  
 3   Under15                        53 non-null     float64
 4   Over60                         53 non-null     float64
 5   FertilityRate                  50 non-null     float64
 6   LifeExpectancy                 53 non-null     int64  
 7   ChildMortality                 53 non-null     float64
 8   CellularSubscribers            51 non-null     float64
 9   LiteracyRate                   26 non-null     float64
 10  GNI                            48 non-null     float64
 11  PrimarySchoolEnrollmentMale    38 non-null     float64
 12  PrimarySchoolEnrollmentFemale  38 non-null     floa

In [74]:
# Other subsets:
WHO_AsiaEurope = WHO[(WHO['Region'] == 'Europe') | (WHO['Region'] == 'South-East Asia') | (WHO['Region'] == "Eastern Mediterranean")] 
WHO_AsiaEurope.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 86 entries, 0 to 191
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Country                        86 non-null     object 
 1   Region                         86 non-null     object 
 2   Population                     86 non-null     int64  
 3   Under15                        86 non-null     float64
 4   Over60                         86 non-null     float64
 5   FertilityRate                  83 non-null     float64
 6   LifeExpectancy                 86 non-null     int64  
 7   ChildMortality                 86 non-null     float64
 8   CellularSubscribers            83 non-null     float64
 9   LiteracyRate                   41 non-null     float64
 10  GNI                            69 non-null     float64
 11  PrimarySchoolEnrollmentMale    48 non-null     float64
 12  PrimarySchoolEnrollmentFemale  48 non-null     floa

In [75]:
WHO_AsiaEurope.to_csv("WHO_AsiaEurope.csv")

In [ ]:
# Your turn:
# How many countries have population greater than 50 million? 


In [79]:
Answer = WHO[WHO['Population'] > 50000]
len(Answer)

25

### Basic Data Analysis

In [80]:
# To access a variable in a data frame, you always have to link it to the data frame and call it using square
# brackets and pass it's name as a string.
LifeExpectancy
# This will give you an error!

NameError: name 'LifeExpectancy' is not defined

In [81]:
# Now, run this.
WHO['LifeExpectancy']

0      60
1      74
2      73
3      82
4      51
       ..
189    75
190    75
191    64
192    55
193    54
Name: LifeExpectancy, Length: 194, dtype: int64

In [91]:
# Statistics about this variable
print((WHO['LifeExpectancy'].mean()))
print((WHO['LifeExpectancy'].max()))
print((WHO['LifeExpectancy'].min()))

70.01030927835052
83
47


In [92]:
# Standard deviation
WHO['LifeExpectancy'].std
WHO['LifeExpectancy'].describe()

count    194.000000
mean      70.010309
std        9.259075
min       47.000000
25%       64.000000
50%       72.500000
75%       76.000000
max       83.000000
Name: LifeExpectancy, dtype: float64

In [93]:
WHO['GNI'].describe()
# what's different here?

count      162.000000
mean     13320.925926
std      15192.988650
min        340.000000
25%       2335.000000
50%       7870.000000
75%      17557.500000
max      86440.000000
Name: GNI, dtype: float64

In [104]:
# Identify countries corresponding to max and min

idx_min = WHO['LifeExpectancy'].argmin()
print(WHO['Country'][idx_min])

idx_max = WHO['LifeExpectancy'].argmax()
print(WHO['Country'][idx_max])

Sierra Leone
Japan


In [ ]:
# Your turn:
# What is the largest population value among all countries?
# Which country has the largest population?



In [112]:
# Dealing with NA (Missing data)
# Try:
WHO['LiteracyRate'].head()

4     70.1
5     99.0
6     97.8
7     99.6
12    91.9
Name: LiteracyRate, dtype: float64

In [114]:
WHO['LiteracyRate'].dropna(inplace=True)
WHO['LiteracyRate'].head()

4     70.1
5     99.0
6     97.8
7     99.6
12    91.9
Name: LiteracyRate, dtype: float64

### Linear Algebra

In [115]:
# https://numpy.org/doc/stable/reference/routines.linalg.html

In [121]:
# (row) vector
a = np.array([1,2,3])
b = np.array([1,1,1])
2*a

array([2, 4, 6])

In [126]:
# element-wise multiplication
np.multiply(a,b)

array([1, 2, 3])

In [127]:
# inner product
np.dot(a,b)

6

In [135]:
# matrix
A = np.array([[1, 2, 8],
             [3, 2, 9]])
print(A)

[[1 2 8]
 [3 2 9]]


In [145]:
# matrix multiplication
B = np.array([[1, 2],
              [3, 8],
              [2, 9]])

# There are tow ways:
np.matmul(A,B)

# or alternatively:
A@B

array([[ 23,  90],
       [ 27, 103]])

In [146]:
# transpose
A.T

array([[1, 3],
       [2, 2],
       [8, 9]])

In [149]:
# inverse
C = np.array([[1, 2],
             [3, 2]])
D = np.linalg.inv(C)
C@D

array([[1.00000000e+00, 5.55111512e-17],
       [0.00000000e+00, 1.00000000e+00]])